### ISSUE TITLE
Add withFormikAdapter

### ISSUE THREAD

**Issue by chawes13** [LaunchPadLab/lp-hoc#145] opened 2020-12-09 20:55 UTC
It'd be nice to standardize this across apps. While technically it is an HOC, it might make more sense to include it as an exported util within `lp-components`?

**Comment by dpikt** [comment] 2020-12-09 21:17
I think this can be considered a duplicate of https://github.com/LaunchPadLab/lp-components/issues/412

**Closed by dpikt** 2020-12-09 21:17 UTC
Labels: idea, question
